---
title: "Untitled"
author: "Romeo Penheiro"
date: "10/02/2022"
output: html_document
---

```{r}
if (!requireNamespace('xfun')) install.packages('xfun')
xf <- loadNamespace('xfun')

cran_packages = c(
        "readr",
        "here",
        "tibble",
        "data.table",
        "tidyverse"
        )
if (length(cran_packages) != 0) xf$pkg_load2(cran_packages)

import::from(magrittr, '%>%')

dp <- import::from(dplyr, .all=TRUE, .into={new.env()})
```

```{r}
list <- list.files(here::here("data/data-raw"))

# Create a data frame for holding all the data
final <- data.frame(NULL)
# Data organized by trial order
trial_count <- data.frame(NULL)

```

```{r}
#Go though each file, extract the relevant info, add a subject number

for(i in 1:length(list)){
        name <- list[i]
        temp <- data.table::fread(here::here("data/data-raw", name), 
                                  select = c("resp.keys",
                                                      "resp.corr",
                                                      "resp.rt",
                                                      "strings",
                                                      "corrans",
                                                      "gender (m/f)",
                                                      "age",
                                                      "freq",
                                                      "trials.thisIndex",
                                                      "OS"))
        # Remove the practice trials
        temp <- temp[-(1:10),]
        # Add subject number
        temp$subject <- i
        # Remove randomization by reordering the rows by the order of the original experiment parameters
        dplyr::arrange(temp, temp$trials.thisIndex)
                # Remove NAs from the index column
                # dp$filter(!is.na(temp$trials.thisIndex))
                # Not required as we removed the practice trials
        # Concatenate successive files
        final <- dplyr::bind_rows(final, temp)

}
```

